name: Deploy to Server

on:
  push:
    branches:
      - main  # ou a branch que vocÃª usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 82.29.184.231
          username: juvenal
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e  # Para parar em caso de erro

            echo "ğŸ“‚ Acessando diretÃ³rio do projeto..."
            cd /home/juvenal/public_html/nextech

            echo "ğŸ”„ Atualizando repositÃ³rio com git pull..."
            git pull origin main

            echo "ğŸ“¦ Instalando dependÃªncias..."
            npm install --production

            echo "âš™ï¸ Buildando aplicaÃ§Ã£o..."
            npm run build --prod

            echo "âœ… Deploy concluÃ­do com sucesso!"
